import "./init";
import "@components/Hero/hero"
import "@components/Header/header"
import "@components/Categories/categories"
import "@components/Expandable/expandable";
import "@components/Slider/slider";
import "@components/Offers/offers";
import "@components/Quantity/quantity";
import "@components/Partnership/partnership";
import "@components/Filter/filter";
import "@components/ProductToolbar/product-toolbar";
import "@components/OTP/otp";
import "@components/Auth/auth";
import "@components/Card/card";
import "@components/OrderSummary/order-summary";
import "@components/Checkout/checkout";
import "@components/CheckoutOptions/checkout-options";
import "@components/CitySelector/city-selector";

import "./demo";