import "./init";
import "@components/Nav/nav"
import "@components/Search/search"
import "@components/Hero/hero"
import "@components/Header/header"
import "@components/Categories/categories"
import "@components/Expandable/expandable";
import "@components/Slider/slider";
import "@components/Offers/offers";
import "@components/Quantity/quantity";
import "@components/Partnership/partnership";
import "@components/Filter/filter";
import "@components/ProductToolbar/product-toolbar";
import "@components/OTP/otp";
import "@components/Auth/auth";
import "@components/OrderSummary/order-summary";
import "@components/CheckoutOptions/checkout-options";
import "@components/CitySelector/city-selector";
import "@components/InputPassword/input-password";
import "@components/EditBtn/edit-btn";
import "@components/Address/address";
import "@components/Orders/orders";
import "@components/Recipes/recipes";

import "./demo";